menjar/config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :donations
  resources :reservations
  resources :offers
  resources :products
  resources :charities
  resources :consumers
  resources :providers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#index"
  get "register/" => "register#index"
  get "facade/" => "facade#index"
  get "about/" => "about#index"
end

menjar/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

menjar/app/models/charity.rb
class Charity < ApplicationRecord
end

menjar/app/models/consumer.rb
class Consumer < ApplicationRecord
end

menjar/app/models/donation.rb
class Donation < ApplicationRecord
end

menjar/app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :product_id
  belongs_to :provider_id
end

menjar/app/models/person.rb
class Person < ApplicationRecord
  belongs_to :provider_id
end

menjar/app/models/product.rb
class Product < ApplicationRecord
end

menjar/app/models/provider.rb
class Provider < ApplicationRecord
end

menjar/app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :provider_id
  belongs_to :consumer_id
end

menjar/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

menjar/app/controllers/facade_controller.rb
class FacadeController < ApplicationController
  def index
  end
end

menjar/app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:amount, :name, :product_id_id, :provider_id_id)
    end
end

menjar/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:cedula, :name, :born_date, :nationality, :provider_id_id)
    end
end

menjar/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @products = Product.all
  end
end

menjar/app/helpers/application_helper.rb
module ApplicationHelper
end

menjar/app/helpers/charities_helper.rb
module CharitiesHelper
end

menjar/app/helpers/consumers_helper.rb
module ConsumersHelper
end

menjar/app/helpers/donations_helper.rb
module DonationsHelper
end

menjar/app/helpers/offers_helper.rb
module OffersHelper
end

menjar/app/helpers/people_helper.rb
module PeopleHelper
end

menjar/app/helpers/products_helper.rb
module ProductsHelper
end

menjar/app/helpers/providers_helper.rb
module ProvidersHelper
end

menjar/app/helpers/reservations_helper.rb
module ReservationsHelper
end

menjar/app/views/offers/_form.html.erb
<%= form_for(offer) do |f| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :product_id_id %>
    <%= f.text_field :product_id_id %>
  </div>

  <div class="field">
    <%= f.label :provider_id_id %>
    <%= f.text_field :provider_id_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

menjar/app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

menjar/app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offers</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Name</th>
      <th>Product</th>
      <th>Provider</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.amount %></td>
        <td><%= offer.name %></td>
        <td><%= offer.product_id %></td>
        <td><%= offer.provider_id %></td>
        <td><%= link_to 'Show', offer %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_offer_path %>

menjar/app/views/offers/new.html.erb
<h1>New Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Back', offers_path %>

menjar/app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @offer.amount %>
</p>

<p>
  <strong>Name:</strong>
  <%= @offer.name %>
</p>

<p>
  <strong>Product:</strong>
  <%= @offer.product_id %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @offer.provider_id %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>

menjar/app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cedula %>
    <%= f.text_field :cedula %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :born_date %>
    <%= f.datetime_select :born_date %>
  </div>

  <div class="field">
    <%= f.label :nationality %>
    <%= f.text_field :nationality %>
  </div>

  <div class="field">
    <%= f.label :provider_id_id %>
    <%= f.text_field :provider_id_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

menjar/app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

menjar/app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Cedula</th>
      <th>Name</th>
      <th>Born date</th>
      <th>Nationality</th>
      <th>Provider</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.cedula %></td>
        <td><%= person.name %></td>
        <td><%= person.born_date %></td>
        <td><%= person.nationality %></td>
        <td><%= person.provider_id %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

menjar/app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

menjar/app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cedula:</strong>
  <%= @person.cedula %>
</p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Born date:</strong>
  <%= @person.born_date %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @person.nationality %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @person.provider_id %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>