menjar/config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :donations
  resources :reservations
  resources :offers
  resources :products
  resources :charities
  resources :consumers
  resources :providers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#index"
  get "register/" => "register#index"
  get "facade/" => "facade#index"
  get "about/" => "about#index"
end

menjar/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

menjar/app/models/charity.rb
class Charity < ApplicationRecord
end

menjar/app/models/consumer.rb
class Consumer < ApplicationRecord
end

menjar/app/models/donation.rb
class Donation < ApplicationRecord
end

menjar/app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :product_id
  belongs_to :provider_id
end

menjar/app/models/person.rb
class Person < ApplicationRecord
  belongs_to :provider_id
end

menjar/app/models/product.rb
class Product < ApplicationRecord
end

menjar/app/models/provider.rb
class Provider < ApplicationRecord
end

menjar/app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :provider_id
  belongs_to :consumer_id
end

menjar/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

menjar/app/controllers/facade_controller.rb
class FacadeController < ApplicationController
  def index
  end
end

menjar/app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:amount, :name, :product_id_id, :provider_id_id)
    end
end

menjar/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:cedula, :name, :born_date, :nationality, :provider_id_id)
    end
end

menjar/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:amount, :description, :limit_date, :date_reservation, :datetime, :provider_id_id, :consumer_id_id)
    end
end

menjar/app/helpers/application_helper.rb
module ApplicationHelper
end

menjar/app/helpers/charities_helper.rb
module CharitiesHelper
end

menjar/app/helpers/consumers_helper.rb
module ConsumersHelper
end

menjar/app/helpers/donations_helper.rb
module DonationsHelper
end

menjar/app/helpers/offers_helper.rb
module OffersHelper
end

menjar/app/helpers/people_helper.rb
module PeopleHelper
end

menjar/app/helpers/products_helper.rb
module ProductsHelper
end

menjar/app/helpers/providers_helper.rb
module ProvidersHelper
end

menjar/app/helpers/reservations_helper.rb
module ReservationsHelper
end

menjar/app/views/reservations/_form.html.erb
<%= form_for(reservation) do |f| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :limit_date %>
    <%= f.datetime_select :limit_date %>
  </div>

  <div class="field">
    <%= f.label :date_reservation %>
    <%= f.text_field :date_reservation %>
  </div>

  <div class="field">
    <%= f.label :datetime %>
    <%= f.text_field :datetime %>
  </div>

  <div class="field">
    <%= f.label :provider_id_id %>
    <%= f.text_field :provider_id_id %>
  </div>

  <div class="field">
    <%= f.label :consumer_id_id %>
    <%= f.text_field :consumer_id_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

menjar/app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

menjar/app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Description</th>
      <th>Limit date</th>
      <th>Date reservation</th>
      <th>Datetime</th>
      <th>Provider</th>
      <th>Consumer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.amount %></td>
        <td><%= reservation.description %></td>
        <td><%= reservation.limit_date %></td>
        <td><%= reservation.date_reservation %></td>
        <td><%= reservation.datetime %></td>
        <td><%= reservation.provider_id %></td>
        <td><%= reservation.consumer_id %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

menjar/app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

menjar/app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @reservation.amount %>
</p>

<p>
  <strong>Description:</strong>
  <%= @reservation.description %>
</p>

<p>
  <strong>Limit date:</strong>
  <%= @reservation.limit_date %>
</p>

<p>
  <strong>Date reservation:</strong>
  <%= @reservation.date_reservation %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @reservation.datetime %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @reservation.provider_id %>
</p>

<p>
  <strong>Consumer:</strong>
  <%= @reservation.consumer_id %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>