menjar/config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :donations
  resources :reservations
  resources :offers
  resources :products
  resources :charities
  resources :consumers
  resources :providers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#index"
  get "register/" => "register#index"
  get "facade/" => "facade#index"
  get "about/" => "about#index"
end

menjar/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

menjar/app/models/charity.rb
class Charity < ApplicationRecord
end

menjar/app/models/consumer.rb
class Consumer < ApplicationRecord
end

menjar/app/models/donation.rb
class Donation < ApplicationRecord
end

menjar/app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :product_id
  belongs_to :provider_id
end

menjar/app/models/person.rb
class Person < ApplicationRecord
  belongs_to :provider_id
end

menjar/app/models/product.rb
class Product < ApplicationRecord
end

menjar/app/models/provider.rb
class Provider < ApplicationRecord
end

menjar/app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :provider_id
  belongs_to :consumer_id
end

menjar/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

menjar/app/controllers/facade_controller.rb
class FacadeController < ApplicationController
  def index
  end
end

menjar/app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:amount, :name, :product_id_id, :provider_id_id)
    end
end

menjar/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:cedula, :name, :born_date, :nationality, :provider_id_id)
    end
end

menjar/app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:name, :description, :born_date)
    end
end

menjar/app/helpers/application_helper.rb
module ApplicationHelper
end

menjar/app/helpers/charities_helper.rb
module CharitiesHelper
end

menjar/app/helpers/consumers_helper.rb
module ConsumersHelper
end

menjar/app/helpers/donations_helper.rb
module DonationsHelper
end

menjar/app/helpers/offers_helper.rb
module OffersHelper
end

menjar/app/helpers/people_helper.rb
module PeopleHelper
end

menjar/app/helpers/products_helper.rb
module ProductsHelper
end

menjar/app/helpers/providers_helper.rb
module ProvidersHelper
end

menjar/app/helpers/reservations_helper.rb
module ReservationsHelper
end

menjar/app/views/providers/_form.html.erb
<%= form_for(provider) do |f| %>
  <% if provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
      <% provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :born_date %>
    <%= f.datetime_select :born_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

menjar/app/views/providers/edit.html.erb
<h1>Editing Provider</h1>

<%= render 'form', provider: @provider %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

menjar/app/views/providers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Providers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Born date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @providers.each do |provider| %>
      <tr>
        <td><%= provider.name %></td>
        <td><%= provider.description %></td>
        <td><%= provider.born_date %></td>
        <td><%= link_to 'Show', provider %></td>
        <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
        <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provider', new_provider_path %>

menjar/app/views/providers/new.html.erb
<h1>New Provider</h1>

<%= render 'form', provider: @provider %>

<%= link_to 'Back', providers_path %>

menjar/app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @provider.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @provider.description %>
</p>

<p>
  <strong>Born date:</strong>
  <%= @provider.born_date %>
</p>

<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>